[server]
headless = true
maxUploadSize = 10

[theme]
base = "dark"
primaryColor = "#818CF8"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0F172A"
textColor = "#E2E8F0"
font = "sans serif"

[browser]
gatherUsageStats = false
